const defaultAgents = [
  {
    id: 'planner',
    name: 'Planner Agent',
    responsibility: 'Converts prompt into a scoped build plan.',
  },
  {
    id: 'architect',
    name: 'Architect Agent',
    responsibility: 'Defines routes, components, and data contracts.',
  },
  {
    id: 'builder',
    name: 'Builder Agent',
    responsibility: 'Generates starter app files.',
  },
  {
    id: 'qa',
    name: 'QA Agent',
    responsibility: 'Runs rule-based checks on generated output.',
  },
  {
    id: 'release',
    name: 'Release Agent',
    responsibility: 'Prepares deploy notes and next actions.',
  },
];

function toSlug(input) {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

function inferDomain(prompt) {
  const lower = prompt.toLowerCase();
  if (lower.includes('crm')) return 'CRM';
  if (lower.includes('ecommerce') || lower.includes('shop')) return 'E-commerce';
  if (lower.includes('health') || lower.includes('clinic')) return 'Healthcare';
  if (lower.includes('fin')) return 'Fintech';
  return 'SaaS';
}

export function runAgentSwarm(prompt) {
  const safePrompt = prompt.trim();
  if (!safePrompt) {
    return {
      error: 'Prompt is required.',
      agents: defaultAgents,
      output: null,
    };
  }

  const projectName = safePrompt.split(' ').slice(0, 5).join(' ');
  const slug = toSlug(projectName || 'vibe-app');
  const domain = inferDomain(safePrompt);

  const plan = [
    'Generate authenticated app shell',
    'Create dashboard + project list views',
    'Wire prompt run history and activity timeline',
    'Prepare deploy metadata and rollout checklist',
  ];

  const files = [
    {
      path: `apps/${slug}/README.md`,
      content: `# ${projectName}\n\nDomain: ${domain}\n\nGenerated by Agent Swarm MVP.`,
    },
    {
      path: `apps/${slug}/src/pages/dashboard.tsx`,
      content:
        "export default function Dashboard(){return <main><h1>Dashboard</h1><p>Agent swarm generated this starter page.</p></main>}",
    },
    {
      path: `apps/${slug}/src/lib/agents.ts`,
      content: `export const agents = ${JSON.stringify(defaultAgents, null, 2)};`,
    },
  ];

  const checks = [
    { name: 'Project has README', pass: files.some((f) => f.path.endsWith('README.md')) },
    { name: 'Dashboard route generated', pass: files.some((f) => f.path.includes('dashboard')) },
    { name: 'Agents manifest created', pass: files.some((f) => f.path.includes('agents.ts')) },
  ];

  const releaseNotes = {
    deploymentTarget: 'Vercel',
    supabaseRequired: true,
    recommendedNextStep: 'Connect generated files to real project/workspace persistence in Supabase.',
  };

  return {
    error: null,
    agents: defaultAgents,
    output: {
      prompt: safePrompt,
      projectName,
      slug,
      domain,
      plan,
      files,
      checks,
      releaseNotes,
      generatedAt: new Date().toISOString(),
    },
  };
}

export function getAgentCount() {
  return defaultAgents.length;
}
